package org.blink.blizz.countryCodePicker.constantsCodePicker
import org.blink.blizz.countryCodePicker.CountryPickerItem
import org.blink.blizz.countryCodePicker.constantsCodePicker.Constants.list
import org.blink.blizz.R

object Constants {
    var list = ArrayList<CountryPickerItem>()
}

fun setCountryList() {
    list.add(
        CountryPickerItem(
            "ad",
            "376",
            "Andorra",
            R.drawable.flag_andorra
        )
    )
    list.add(
        CountryPickerItem(
            "ae",
            "971",
            "United Arab Emirates (UAE)",
            R.drawable.flag_uae
        )
    )
    list.add(
        CountryPickerItem(
            "af",
            "93",
            "Afghanistan",
            R.drawable.flag_afghanistan
        )
    )
    list.add(
        CountryPickerItem(
            "ag",
            "1",
            "Antigua and Barbuda",
            R.drawable.flag_antigua_and_barbuda
        )
    )
    list.add(
        CountryPickerItem(
            "ai",
            "1",
            "Anguilla",
            R.drawable.flag_anguilla
        )
    )
    list.add(
        CountryPickerItem(
            "al",
            "355",
            "Albania",
            R.drawable.flag_albania
        )
    )
    list.add(
        CountryPickerItem(
            "am",
            "374",
            "Armenia",
            R.drawable.flag_armenia
        )
    )
    list.add(
        CountryPickerItem(
            "ao",
            "244",
            "Angola",
            R.drawable.flag_angola
        )
    )
    list.add(
        CountryPickerItem(
            "aq",
            "672",
            "Antarctica",
            R.drawable.flag_antarctica
        )
    )
    list.add(
        CountryPickerItem(
            "ar",
            "54",
            "Argentina",
            R.drawable.flag_argentina
        )
    )
    list.add(
        CountryPickerItem(
            "as",
            "1",
            "American Samoa",
            R.drawable.flag_american_samoa
        )
    )
    list.add(
        CountryPickerItem(
            "at",
            "43",
            "Austria",
            R.drawable.flag_austria
        )
    )
    list.add(
        CountryPickerItem(
            "au",
            "61",
            "Australia",
            R.drawable.flag_australia
        )
    )
    list.add(
        CountryPickerItem(
            "aw",
            "297",
            "Aruba",
            R.drawable.flag_aruba
        )
    )
    list.add(
        CountryPickerItem(
            "ax",
            "358",
            "Åland Islands",
            R.drawable.flag_aland
        )
    )
    list.add(
        CountryPickerItem(
            "az",
            "994",
            "Azerbaijan",
            R.drawable.flag_azerbaijan
        )
    )
    list.add(
        CountryPickerItem(
            "ba",
            "387",
            "Bosnia And Herzegovina",
            R.drawable.flag_bosnia
        )
    )
    list.add(
        CountryPickerItem(
            "bb",
            "1",
            "Barbados",
            R.drawable.flag_barbados
        )
    )
    list.add(
        CountryPickerItem(
            "bd",
            "880",
            "Bangladesh",
            R.drawable.flag_bangladesh
        )
    )
    list.add(
        CountryPickerItem(
            "be",
            "32",
            "Belgium",
            R.drawable.flag_belgium
        )
    )
    list.add(
        CountryPickerItem(
            "bf",
            "226",
            "Burkina Faso",
            R.drawable.flag_burkina_faso
        )
    )
    list.add(
        CountryPickerItem(
            "bg",
            "359",
            "Bulgaria",
            R.drawable.flag_bulgaria
        )
    )
    list.add(
        CountryPickerItem(
            "bh",
            "973",
            "Bahrain",
            R.drawable.flag_bahrain
        )
    )
    list.add(
        CountryPickerItem(
            "bi",
            "257",
            "Burundi",
            R.drawable.flag_burundi
        )
    )
    list.add(
        CountryPickerItem(
            "bj",
            "229",
            "Benin",
            R.drawable.flag_benin
        )
    )
    list.add(
        CountryPickerItem(
            "bl",
            "590",
            "Saint Barthélemy",
            R.drawable.flag_saint_barthelemy
        )
    )
    list.add(
        CountryPickerItem(
            "bm",
            "1",
            "Bermuda",
            R.drawable.flag_bermuda
        )
    )
    list.add(
        CountryPickerItem(
            "bn",
            "673",
            "Brunei Darussalam",
            R.drawable.flag_brunei
        )
    )
    list.add(
        CountryPickerItem(
            "bo",
            "591",
            "Bolivia, Plurinational State Of",
            R.drawable.flag_bolivia
        )
    )
    list.add(
        CountryPickerItem(
            "br",
            "55",
            "Brazil",
            R.drawable.flag_brazil
        )
    )
    list.add(
        CountryPickerItem(
            "bs",
            "1",
            "Bahamas",
             R.drawable.flag_bahamas
        )
    )
    list.add(
        CountryPickerItem(
            "bt",
            "975",
            "Bhutan",
             R.drawable.flag_bhutan
        )
    )
    list.add(
        CountryPickerItem(
            "bw",
            "267",
            "Botswana",
             R.drawable.flag_botswana
        )
    )
    list.add(
        CountryPickerItem(
            "by",
            "375",
            "Belarus",
             R.drawable.flag_belarus
        )
    )
    list.add(
        CountryPickerItem(
            "bz",
            "501",
            "Belize",
             R.drawable.flag_belize
        )
    )
    list.add(
        CountryPickerItem(
            "ca",
            "1",
            "Canada",
             R.drawable.flag_canada
        )
    )
    list.add(
        CountryPickerItem(
            "cc",
            "61",
            "Cocos (keeling) Islands",
             R.drawable.flag_cocos
        )
    )
    list.add(
        CountryPickerItem(
            "cd",
            "243",
            "Congo, The Democratic Republic Of The",
             R.drawable.flag_democratic_republic_of_the_congo
        )
    )
    list.add(
        CountryPickerItem(
            "cf",
            "236",
            "Central African Republic",
             R.drawable.flag_central_african_republic
        )
    )
    list.add(
        CountryPickerItem(
            "cg",
            "242",
            "Congo",
             R.drawable.flag_republic_of_the_congo
        )
    )
    list.add(
        CountryPickerItem(
            "ch",
            "41",
            "Switzerland",
             R.drawable.flag_switzerland
        )
    )
    list.add(
        CountryPickerItem(
            "ci",
            "225",
            "Côte D'ivoire",
             R.drawable.flag_cote_divoire
        )
    )
    list.add(
        CountryPickerItem(
            "ck",
            "682",
            "Cook Islands",
             R.drawable.flag_cook_islands
        )
    )
    list.add(
        CountryPickerItem(
            "cl",
            "56",
            "Chile",
             R.drawable.flag_chile
        )
    )
    list.add(
        CountryPickerItem(
            "cm",
            "237",
            "Cameroon",
             R.drawable.flag_cameroon
        )
    )
    list.add(
        CountryPickerItem(
            "cn",
            "86",
            "China",
             R.drawable.flag_china
        )
    )
    list.add(
        CountryPickerItem(
            "co",
            "57",
            "Colombia",
             R.drawable.flag_colombia
        )
    )
    list.add(
        CountryPickerItem(
            "cr",
            "506",
            "Costa Rica",
             R.drawable.flag_costa_rica
        )
    )
    list.add(
        CountryPickerItem(
            "cu",
            "53",
            "Cuba",
             R.drawable.flag_cuba
        )
    )
    list.add(
        CountryPickerItem(
            "cv",
            "238",
            "Cape Verde",
             R.drawable.flag_cape_verde
        )
    )
    list.add(
        CountryPickerItem(
            "cw",
            "599",
            "Curaçao",
             R.drawable.flag_curacao
        )
    )
    list.add(
        CountryPickerItem(
            "cx",
            "61",
            "Christmas Island",
             R.drawable.flag_christmas_island
        )
    )
    list.add(
        CountryPickerItem(
            "cy",
            "357",
            "Cyprus",
             R.drawable.flag_cyprus
        )
    )
    list.add(
        CountryPickerItem(
            "cz",
            "420",
            "Czech Republic",
             R.drawable.flag_czech_republic
        )
    )
    list.add(
        CountryPickerItem(
            "de",
            "49",
            "Germany",
             R.drawable.flag_germany
        )
    )
    list.add(
        CountryPickerItem(
            "dj",
            "253",
            "Djibouti",
             R.drawable.flag_djibouti
        )
    )
    list.add(
        CountryPickerItem(
            "dk",
            "45",
            "Denmark",
             R.drawable.flag_denmark
        )
    )
    list.add(
        CountryPickerItem(
            "dm",
            "1",
            "Dominica",
             R.drawable.flag_dominica
        )
    )
    list.add(
        CountryPickerItem(
            "do",
            "1",
            "Dominican Republic",
             R.drawable.flag_dominican_republic
        )
    )
    list.add(
        CountryPickerItem(
            "dz",
            "213",
            "Algeria",
             R.drawable.flag_algeria
        )
    )
    list.add(
        CountryPickerItem(
            "ec",
            "593",
            "Ecuador",
             R.drawable.flag_ecuador
        )
    )
    list.add(
        CountryPickerItem(
            "ee",
            "372",
            "Estonia",
             R.drawable.flag_estonia
        )
    )
    list.add(
        CountryPickerItem(
            "eg",
            "20",
            "Egypt",
             R.drawable.flag_egypt
        )
    )
    list.add(
        CountryPickerItem(
            "er",
            "291",
            "Eritrea",
             R.drawable.flag_eritrea
        )
    )
    list.add(
        CountryPickerItem(
            "es",
            "34",
            "Spain",
             R.drawable.flag_spain
        )
    )
    list.add(
        CountryPickerItem(
            "et",
            "251",
            "Ethiopia",
             R.drawable.flag_ethiopia
        )
    )
    list.add(
        CountryPickerItem(
            "fi",
            "358",
            "Finland",
             R.drawable.flag_finland
        )
    )
    list.add(
        CountryPickerItem(
            "fj",
            "679",
            "Fiji",
             R.drawable.flag_fiji
        )
    )
    list.add(
        CountryPickerItem(
            "fk",
            "500",
            "Falkland Islands (malvinas)",
             R.drawable.flag_falkland_islands
        )
    )
    list.add(
        CountryPickerItem(
            "fm",
            "691",
            "Micronesia, Federated States Of",
             R.drawable.flag_micronesia
        )
    )
    list.add(
        CountryPickerItem(
            "fo",
            "298",
            "Faroe Islands",
             R.drawable.flag_faroe_islands
        )
    )
    list.add(
        CountryPickerItem(
            "fr",
            "33",
            "France",
             R.drawable.flag_france
        )
    )
    list.add(
        CountryPickerItem(
            "ga",
            "241",
            "Gabon",
             R.drawable.flag_gabon
        )
    )
    list.add(
        CountryPickerItem(
            "gb",
            "44",
            "United Kingdom",
             R.drawable.flag_united_kingdom
        )
    )
    list.add(
        CountryPickerItem(
            "gd",
            "1",
            "Grenada",
             R.drawable.flag_grenada
        )
    )
    list.add(
        CountryPickerItem(
            "ge",
            "995",
            "Georgia",
             R.drawable.flag_georgia
        )
    )
    list.add(
        CountryPickerItem(
            "gf",
            "594",
            "French Guyana",
             R.drawable.flag_guyane
        )
    )
    list.add(
        CountryPickerItem(
            "gh",
            "233",
            "Ghana",
             R.drawable.flag_ghana
        )
    )
    list.add(
        CountryPickerItem(
            "gi",
            "350",
            "Gibraltar",
             R.drawable.flag_gibraltar
        )
    )
    list.add(
        CountryPickerItem(
            "gl",
            "299",
            "Greenland",
             R.drawable.flag_greenland
        )
    )
    list.add(
        CountryPickerItem(
            "gm",
            "220",
            "Gambia",
             R.drawable.flag_gambia
        )
    )
    list.add(
        CountryPickerItem(
            "gn",
            "224",
            "Guinea",
             R.drawable.flag_guinea
        )
    )
    list.add(
        CountryPickerItem(
            "gp",
            "450",
            "Guadeloupe",
             R.drawable.flag_guadeloupe
        )
    )
    list.add(
        CountryPickerItem(
            "gq",
            "240",
            "Equatorial Guinea",
             R.drawable.flag_equatorial_guinea
        )
    )
    list.add(
        CountryPickerItem(
            "gr",
            "30",
            "Greece",
             R.drawable.flag_greece
        )
    )
    list.add(
        CountryPickerItem(
            "gt",
            "502",
            "Guatemala",
             R.drawable.flag_guatemala
        )
    )
    list.add(
        CountryPickerItem(
            "gu",
            "1",
            "Guam",
             R.drawable.flag_guam
        )
    )
    list.add(
        CountryPickerItem(
            "gw",
            "245",
            "Guinea-bissau",
             R.drawable.flag_guinea_bissau
        )
    )
    list.add(
        CountryPickerItem(
            "gy",
            "592",
            "Guyana",
             R.drawable.flag_guyana
        )
    )
    list.add(
        CountryPickerItem(
            "hk",
            "852",
            "Hong Kong",
             R.drawable.flag_hong_kong
        )
    )
    list.add(
        CountryPickerItem(
            "hn",
            "504",
            "Honduras",
             R.drawable.flag_honduras
        )
    )
    list.add(
        CountryPickerItem(
            "hr",
            "385",
            "Croatia",
             R.drawable.flag_croatia
        )
    )
    list.add(
        CountryPickerItem(
            "ht",
            "509",
            "Haiti",
             R.drawable.flag_haiti
        )
    )
    list.add(
        CountryPickerItem(
            "hu",
            "36",
            "Hungary",
             R.drawable.flag_hungary
        )
    )
    list.add(
        CountryPickerItem(
            "id",
            "62",
            "Indonesia",
             R.drawable.flag_indonesia
        )
    )
    list.add(
        CountryPickerItem(
            "ie",
            "353",
            "Ireland",
             R.drawable.flag_ireland
        )
    )
    list.add(
        CountryPickerItem(
            "il",
            "972",
            "Israel",
             R.drawable.flag_israel
        )
    )
    list.add(
        CountryPickerItem(
            "im",
            "44",
            "Isle Of Man",
             R.drawable.flag_isleof_man
        )
    )
    list.add(
        CountryPickerItem(
            "is",
            "354",
            "Iceland",
             R.drawable.flag_iceland
        )
    )
    list.add(
        CountryPickerItem(
            "in",
            "91",
            "India",
             R.drawable.flag_india
        )
    )
    list.add(
        CountryPickerItem(
            "io",
            "246",
            "British Indian Ocean Territory",
             R.drawable.flag_british_indian_ocean_territory
        )
    )
    list.add(
        CountryPickerItem(
            "iq",
            "964",
            "Iraq",
             R.drawable.flag_iraq_new
        )
    )
    list.add(
        CountryPickerItem(
            "ir",
            "98",
            "Iran, Islamic Republic Of",
             R.drawable.flag_iran
        )
    )
    list.add(
        CountryPickerItem(
            "it",
            "39",
            "Italy",
             R.drawable.flag_italy
        )
    )
    list.add(
        CountryPickerItem(
            "je",
            "44",
            "Jersey ",
             R.drawable.flag_jersey
        )
    )
    list.add(
        CountryPickerItem(
            "jm",
            "1",
            "Jamaica",
             R.drawable.flag_jamaica
        )
    )
    list.add(
        CountryPickerItem(
            "jo",
            "962",
            "Jordan",
             R.drawable.flag_jordan
        )
    )
    list.add(
        CountryPickerItem(
            "jp",
            "81",
            "Japan",
             R.drawable.flag_japan
        )
    )
    list.add(
        CountryPickerItem(
            "ke",
            "254",
            "Kenya",
             R.drawable.flag_kenya
        )
    )
    list.add(
        CountryPickerItem(
            "kg",
            "996",
            "Kyrgyzstan",
             R.drawable.flag_kyrgyzstan
        )
    )
    list.add(
        CountryPickerItem(
            "kh",
            "855",
            "Cambodia",
             R.drawable.flag_cambodia
        )
    )
    list.add(
        CountryPickerItem(
            "ki",
            "686",
            "Kiribati",
             R.drawable.flag_kiribati
        )
    )
    list.add(
        CountryPickerItem(
            "km",
            "269",
            "Comoros",
             R.drawable.flag_comoros
        )
    )
    list.add(
        CountryPickerItem(
            "kn",
            "1",
            "Saint Kitts and Nevis",
             R.drawable.flag_saint_kitts_and_nevis
        )
    )
    list.add(
        CountryPickerItem(
            "kp",
            "850",
            "North Korea",
             R.drawable.flag_north_korea
        )
    )
    list.add(
        CountryPickerItem(
            "kr",
            "82",
            "South Korea",
             R.drawable.flag_south_korea
        )
    )
    list.add(
        CountryPickerItem(
            "kw",
            "965",
            "Kuwait",
             R.drawable.flag_kuwait
        )
    )
    list.add(
        CountryPickerItem(
            "ky",
            "1",
            "Cayman Islands",
             R.drawable.flag_cayman_islands
        )
    )
    list.add(
        CountryPickerItem(
            "kz",
            "7",
            "Kazakhstan",
             R.drawable.flag_kazakhstan
        )
    )
    list.add(
        CountryPickerItem(
            "la",
            "856",
            "Lao People's Democratic Republic",
             R.drawable.flag_laos
        )
    )
    list.add(
        CountryPickerItem(
            "lb",
            "961",
            "Lebanon",
             R.drawable.flag_lebanon
        )
    )
    list.add(
        CountryPickerItem(
            "lc",
            "1",
            "Saint Lucia",
             R.drawable.flag_saint_lucia
        )
    )
    list.add(
        CountryPickerItem(
            "li",
            "423",
            "Liechtenstein",
             R.drawable.flag_liechtenstein
        )
    )
    list.add(
        CountryPickerItem(
            "lk",
            "94",
            "Sri Lanka",
             R.drawable.flag_sri_lanka
        )
    )
    list.add(
        CountryPickerItem(
            "lr",
            "231",
            "Liberia",
             R.drawable.flag_liberia
        )
    )
    list.add(
        CountryPickerItem(
            "ls",
            "266",
            "Lesotho",
             R.drawable.flag_lesotho
        )
    )
    list.add(
        CountryPickerItem(
            "lt",
            "370",
            "Lithuania",
             R.drawable.flag_lithuania
        )
    )
    list.add(
        CountryPickerItem(
            "lu",
            "352",
            "Luxembourg",
             R.drawable.flag_luxembourg
        )
    )
    list.add(
        CountryPickerItem(
            "lv",
            "371",
            "Latvia",
             R.drawable.flag_latvia
        )
    )
    list.add(
        CountryPickerItem(
            "ly",
            "218",
            "Libya",
             R.drawable.flag_libya
        )
    )
    list.add(
        CountryPickerItem(
            "ma",
            "212",
            "Morocco",
             R.drawable.flag_morocco
        )
    )
    list.add(
        CountryPickerItem(
            "mc",
            "377",
            "Monaco",
             R.drawable.flag_monaco
        )
    )
    list.add(
        CountryPickerItem(
            "md",
            "373",
            "Moldova, Republic Of",
             R.drawable.flag_moldova
        )
    )
    list.add(
        CountryPickerItem(
            "me",
            "382",
            "Montenegro",
             R.drawable.flag_of_montenegro
        )
    )
    list.add(
        CountryPickerItem(
            "mf",
            "590",
            "Saint Martin",
             R.drawable.flag_saint_martin
        )
    )
    list.add(
        CountryPickerItem(
            "mg",
            "261",
            "Madagascar",
             R.drawable.flag_madagascar
        )
    )
    list.add(
        CountryPickerItem(
            "mh",
            "692",
            "Marshall Islands",
             R.drawable.flag_marshall_islands
        )
    )
    list.add(
        CountryPickerItem(
            "mk",
            "389",
            "Macedonia (FYROM)",
             R.drawable.flag_macedonia
        )
    )
    list.add(
        CountryPickerItem(
            "ml",
            "223",
            "Mali",
             R.drawable.flag_mali
        )
    )
    list.add(
        CountryPickerItem(
            "mm",
            "95",
            "Myanmar",
             R.drawable.flag_myanmar
        )
    )
    list.add(
        CountryPickerItem(
            "mn",
            "976",
            "Mongolia",
             R.drawable.flag_mongolia
        )
    )
    list.add(
        CountryPickerItem(
            "mo",
            "853",
            "Macao",
             R.drawable.flag_macao
        )
    )
    list.add(
        CountryPickerItem(
            "mp",
            "1",
            "Northern Mariana Islands",
             R.drawable.flag_northern_mariana_islands
        )
    )
    list.add(
        CountryPickerItem(
            "mq",
            "596",
            "Martinique",
             R.drawable.flag_martinique
        )
    )
    list.add(
        CountryPickerItem(
            "mr",
            "222",
            "Mauritania",
             R.drawable.flag_mauritania
        )
    )
    list.add(
        CountryPickerItem(
            "ms",
            "1",
            "Montserrat",
             R.drawable.flag_montserrat
        )
    )
    list.add(
        CountryPickerItem(
            "mt",
            "356",
            "Malta",
             R.drawable.flag_malta
        )
    )
    list.add(
        CountryPickerItem(
            "mu",
            "230",
            "Mauritius",
             R.drawable.flag_mauritius
        )
    )
    list.add(
        CountryPickerItem(
            "mv",
            "960",
            "Maldives",
             R.drawable.flag_maldives
        )
    )
    list.add(
        CountryPickerItem(
            "mw",
            "265",
            "Malawi",
             R.drawable.flag_malawi
        )
    )
    list.add(
        CountryPickerItem(
            "mx",
            "52",
            "Mexico",
             R.drawable.flag_mexico
        )
    )
    list.add(
        CountryPickerItem(
            "my",
            "60",
            "Malaysia",
             R.drawable.flag_malaysia
        )
    )
    list.add(
        CountryPickerItem(
            "mz",
            "258",
            "Mozambique",
             R.drawable.flag_mozambique
        )
    )
    list.add(
        CountryPickerItem(
            "na",
            "264",
            "Namibia",
             R.drawable.flag_namibia
        )
    )
    list.add(
        CountryPickerItem(
            "nc",
            "687",
            "New Caledonia",
             R.drawable.flag_new_caledonia
        )
    )
    list.add(
        CountryPickerItem(
            "ne",
            "227",
            "Niger",
             R.drawable.flag_niger
        )
    )
    list.add(
        CountryPickerItem(
            "nf",
            "672",
            "Norfolk Islands",
             R.drawable.flag_norfolk_island
        )
    )
    list.add(
        CountryPickerItem(
            "ng",
            "234",
            "Nigeria",
             R.drawable.flag_nigeria
        )
    )
    list.add(
        CountryPickerItem(
            "ni",
            "505",
            "Nicaragua",
             R.drawable.flag_nicaragua
        )
    )
    list.add(
        CountryPickerItem(
            "nl",
            "31",
            "Netherlands",
             R.drawable.flag_netherlands
        )
    )
    list.add(
        CountryPickerItem(
            "no",
            "47",
            "Norway",
             R.drawable.flag_norway
        )
    )
    list.add(
        CountryPickerItem(
            "np",
            "977",
            "Nepal",
             R.drawable.flag_nepal
        )
    )
    list.add(
        CountryPickerItem(
            "nr",
            "674",
            "Nauru",
             R.drawable.flag_nauru
        )
    )
    list.add(
        CountryPickerItem(
            "nu",
            "683",
            "Niue",
             R.drawable.flag_niue
        )
    )
    list.add(
        CountryPickerItem(
            "nz",
            "64",
            "New Zealand",
             R.drawable.flag_new_zealand
        )
    )
    list.add(
        CountryPickerItem(
            "om",
            "968",
            "Oman",
             R.drawable.flag_oman
        )
    )
    list.add(
        CountryPickerItem(
            "pa",
            "507",
            "Panama",
             R.drawable.flag_panama
        )
    )
    list.add(
        CountryPickerItem(
            "pe",
            "51",
            "Peru",
             R.drawable.flag_peru
        )
    )
    list.add(
        CountryPickerItem(
            "pf",
            "689",
            "French Polynesia",
             R.drawable.flag_french_polynesia
        )
    )
    list.add(
        CountryPickerItem(
            "pg",
            "675",
            "Papua New Guinea",
             R.drawable.flag_papua_new_guinea
        )
    )
    list.add(
        CountryPickerItem(
            "ph",
            "63",
            "Philippines",
             R.drawable.flag_philippines
        )
    )
    list.add(
        CountryPickerItem(
            "pk",
            "92",
            "Pakistan",
             R.drawable.flag_pakistan
        )
    )
    list.add(
        CountryPickerItem(
            "pl",
            "48",
            "Poland",
             R.drawable.flag_poland
        )
    )
    list.add(
        CountryPickerItem(
            "pm",
            "508",
            "Saint Pierre And Miquelon",
             R.drawable.flag_saint_pierre
        )
    )
    list.add(
        CountryPickerItem(
            "pn",
            "870",
            "Pitcairn Islands",
             R.drawable.flag_pitcairn_islands
        )
    )
    list.add(
        CountryPickerItem(
            "pr",
            "1",
            "Puerto Rico",
             R.drawable.flag_puerto_rico
        )
    )
    list.add(
        CountryPickerItem(
            "ps",
            "970",
            "Palestine",
             R.drawable.flag_palestine
        )
    )
    list.add(
        CountryPickerItem(
            "pt",
            "351",
            "Portugal",
             R.drawable.flag_portugal
        )
    )
    list.add(
        CountryPickerItem(
            "pw",
            "680",
            "Palau",
             R.drawable.flag_palau
        )
    )
    list.add(
        CountryPickerItem(
            "py",
            "595",
            "Paraguay",
             R.drawable.flag_paraguay
        )
    )
    list.add(
        CountryPickerItem(
            "qa",
            "974",
            "Qatar",
             R.drawable.flag_qatar
        )
    )
    list.add(
        CountryPickerItem(
            "re",
            "262",
            "Réunion",
             R.drawable.flag_transparent //no flag
        )
    )
    list.add(
        CountryPickerItem(
            "ro",
            "40",
            "Romania",
             R.drawable.flag_romania
        )
    )
    list.add(
        CountryPickerItem(
            "rs",
            "381",
            "Serbia",
             R.drawable.flag_serbia
        )
    )
    list.add(
        CountryPickerItem(
            "ru",
            "7",
            "Russian Federation",
             R.drawable.flag_russian_federation
        )
    )
    list.add(
        CountryPickerItem(
            "rw",
            "250",
            "Rwanda",
             R.drawable.flag_rwanda
        )
    )
    list.add(
        CountryPickerItem(
            "sa",
            "966",
            "Saudi Arabia",
             R.drawable.flag_saudi_arabia
        )
    )
    list.add(
        CountryPickerItem(
            "sb",
            "677",
            "Solomon Islands",
             R.drawable.flag_soloman_islands
        )
    )
    list.add(
        CountryPickerItem(
            "sc",
            "248",
            "Seychelles",
             R.drawable.flag_seychelles
        )
    )
    list.add(
        CountryPickerItem(
            "sd",
            "249",
            "Sudan",
             R.drawable.flag_sudan
        )
    )
    list.add(
        CountryPickerItem(
            "se",
            "46",
            "Sweden",
             R.drawable.flag_sweden
        )
    )
    list.add(
        CountryPickerItem(
            "sg",
            "65",
            "Singapore",
             R.drawable.flag_singapore
        )
    )
    list.add(
        CountryPickerItem(
            "sh",
            "290",
            "Saint Helena, Ascension And Tristan Da Cunha",
             R.drawable.flag_saint_helena
        )
    )
    list.add(
        CountryPickerItem(
            "si",
            "386",
            "Slovenia",
             R.drawable.flag_slovenia
        )
    )
    list.add(
        CountryPickerItem(
            "sk",
            "421",
            "Slovakia",
             R.drawable.flag_slovakia
        )
    )
    list.add(
        CountryPickerItem(
            "sl",
            "232",
            "Sierra Leone",
             R.drawable.flag_sierra_leone
        )
    )
    list.add(
        CountryPickerItem(
            "sm",
            "378",
            "San Marino",
             R.drawable.flag_san_marino
        )
    )
    list.add(
        CountryPickerItem(
            "sn",
            "221",
            "Senegal",
             R.drawable.flag_senegal
        )
    )
    list.add(
        CountryPickerItem(
            "so",
            "252",
            "Somalia",
             R.drawable.flag_somalia
        )
    )
    list.add(
        CountryPickerItem(
            "sr",
            "597",
            "Suriname",
             R.drawable.flag_suriname
        )
    )
    list.add(
        CountryPickerItem(
            "ss",
            "211",
            "South Sudan",
             R.drawable.flag_south_sudan
        )
    )
    list.add(
        CountryPickerItem(
            "st",
            "239",
            "Sao Tome And Principe",
             R.drawable.flag_sao_tome_and_principe
        )
    )
    list.add(
        CountryPickerItem(
            "sv",
            "503",
            "El Salvador",
             R.drawable.flag_el_salvador
        )
    )
    list.add(
        CountryPickerItem(
            "sx",
            "1",
            "Sint Maarten",
             R.drawable.flag_sint_maarten
        )
    )
    list.add(
        CountryPickerItem(
            "sy",
            "963",
            "Syrian Arab Republic",
             R.drawable.flag_syria
        )
    )
    list.add(
        CountryPickerItem(
            "sz",
            "268",
            "Swaziland",
             R.drawable.flag_swaziland
        )
    )
    list.add(
        CountryPickerItem(
            "tc",
            "1",
            "Turks and Caicos Islands",
             R.drawable.flag_turks_and_caicos_islands
        )
    )
    list.add(
        CountryPickerItem(
            "td",
            "235",
            "Chad",
             R.drawable.flag_chad
        )
    )
    list.add(
        CountryPickerItem(
            "tg",
            "228",
            "Togo",
             R.drawable.flag_togo
        )
    )
    list.add(
        CountryPickerItem(
            "th",
            "66",
            "Thailand",
             R.drawable.flag_thailand
        )
    )
    list.add(
        CountryPickerItem(
            "tj",
            "992",
            "Tajikistan",
             R.drawable.flag_tajikistan
        )
    )
    list.add(
        CountryPickerItem(
            "tk",
            "690",
            "Tokelau",
             R.drawable.flag_tokelau
        )
    )
    list.add(
        CountryPickerItem(
            "tl",
            "670",
            "Timor-leste",
             R.drawable.flag_timor_leste
        )
    )
    list.add(
        CountryPickerItem(
            "tm",
            "993",
            "Turkmenistan",
             R.drawable.flag_turkmenistan
        )
    )
    list.add(
        CountryPickerItem(
            "tn",
            "216",
            "Tunisia",
             R.drawable.flag_tunisia
        )
    )
    list.add(
        CountryPickerItem(
            "to",
            "676",
            "Tonga",
             R.drawable.flag_tonga
        )
    )
    list.add(
        CountryPickerItem(
            "tr",
            "90",
            "Turkey",
             R.drawable.flag_turkey
        )
    )
    list.add(
        CountryPickerItem(
            "tt",
            "1",
            "Trinidad &amp; Tobago",
             R.drawable.flag_trinidad_and_tobago
        )
    )
    list.add(
        CountryPickerItem(
            "tv",
            "688",
            "Tuvalu",
             R.drawable.flag_tuvalu
        )
    )
    list.add(
        CountryPickerItem(
            "tw",
            "886",
            "Taiwan",
             R.drawable.flag_taiwan
        )
    )
    list.add(
        CountryPickerItem(
            "tz",
            "255",
            "Tanzania, United Republic Of",
             R.drawable.flag_tanzania
        )
    )
    list.add(
        CountryPickerItem(
            "ua",
            "380",
            "Ukraine",
             R.drawable.flag_ukraine
        )
    )
    list.add(
        CountryPickerItem(
            "ug",
            "256",
            "Uganda",
             R.drawable.flag_uganda
        )
    )
    list.add(
        CountryPickerItem(
            "us",
            "1",
            "United States",
             R.drawable.flag_united_states_of_america
        )
    )
    list.add(
        CountryPickerItem(
            "uy",
            "598",
            "Uruguay",
             R.drawable.flag_uruguay
        )
    )
    list.add(
        CountryPickerItem(
            "uz",
            "998",
            "Uzbekistan",
             R.drawable.flag_uzbekistan
        )
    )
    list.add(
        CountryPickerItem(
            "va",
            "379",
            "Holy See (vatican City State)",
             R.drawable.flag_vatican_city
        )
    )
    list.add(
        CountryPickerItem(
            "vc",
            "1",
            "Saint Vincent &amp; The Grenadines",
             R.drawable.flag_saint_vicent_and_the_grenadines
        )
    )
    list.add(
        CountryPickerItem(
            "ve",
            "58",
            "Venezuela, Bolivarian Republic Of",
             R.drawable.flag_venezuela
        )
    )
    list.add(
        CountryPickerItem(
            "vg",
            "1",
            "British Virgin Islands",
             R.drawable.flag_british_virgin_islands
        )
    )
    list.add(
        CountryPickerItem(
            "vi",
            "1",
            "US Virgin Islands",
             R.drawable.flag_us_virgin_islands
        )
    )
    list.add(
        CountryPickerItem(
            "vn",
            "84",
            "Vietnam",
             R.drawable.flag_vietnam
        )
    )
    list.add(
        CountryPickerItem(
            "vu",
            "678",
            "Vanuatu",
             R.drawable.flag_vanuatu
        )
    )
    list.add(
        CountryPickerItem(
            "wf",
            "681",
            "Wallis And Futuna",
             R.drawable.flag_wallis_and_futuna
        )
    )
    list.add(
        CountryPickerItem(
            "ws",
            "685",
            "Samoa",
             R.drawable.flag_samoa
        )
    )
    list.add(
        CountryPickerItem(
            "xk",
            "383",
            "Kosovo",
             R.drawable.flag_kosovo
        )
    )
    list.add(
        CountryPickerItem(
            "ye",
            "967",
            "Yemen",
             R.drawable.flag_yemen
        )
    )
    list.add(
        CountryPickerItem(
            "yt",
            "262",
            "Mayotte",
             R.drawable.flag_transparent //no flag
        )
    )
    list.add(
        CountryPickerItem(
            "za",
            "27",
            "South Africa",
             R.drawable.flag_south_africa
        )
    )
    list.add(
        CountryPickerItem(
            "zm",
            "260",
            "Zambia",
             R.drawable.flag_zambia
        )
    )
    list.add(
        CountryPickerItem(
            "zw",
            "263",
            "Zimbabwe",
             R.drawable.flag_zimbabwe
        )
    )
}

